# Generated by Django 3.0.2 on 2020-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='image_books/')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='books/')),
            ],
        ),
    ]
